language: ruby
rvm:
- 2.2.0
- 2.1.5
env:
- DATABASE_USER="postgres" NOCOVERAGE="true" JRUBY_OPTS="-J-Xmx2048m"
addons:
  postgresql: '9.3'
script: bundle exec rake travis --trace
before_script:
- psql -c 'create database "horizon_test";' -U postgres
- psql -c 'create database "hayashi_test";' -U postgres
notifications:
  slack:
    secure: Dgq+CT78IlxqXByWWzUmc72/Qvw7HpxzzWIUIR7AyE9yO6w2Fr6rfLjotql75pMXtfTCPjxDK2u9mUT2MehgSWGeXssSzy/QM/pxCINZfzTNhhcAjKq5WEwQ2oVdSxcXv4ukp9K0wFsT3ca3wEtaOHBT5wDXvW/qI6ru+dhaJvI=
